### ISSUE TITLE
setting the item size property to large for the including region

### ISSUE THREAD

**Issue by aymanwkh** [mennooo/orclapex-modal-lov#1]
I created a new application to test the plugin (Apex 18.1), when setting the item size for the including region to large the item appears as follows :

![modal_lov](https://user-images.githubusercontent.com/23289338/40638469-27345de0-6314-11e8-82bd-df38a403791f.png)

**Comment by mennooo** [comment]
Confirmed, the CSS needs to be updated for region-level template options.

**Comment by aymanwkh** [comment]
Hi,
this css snippet solves the issue :

.t-Form--large .t-Form-inputContainer .search-clear {
    padding: 0px;
}
