### ISSUE TITLE
inconsistent of clear icon position

### ISSUE THREAD

**Issue by aymanwkh** [mennooo/orclapex-modal-lov#12]
After upgrading to 1.1, when opening a dialog that contains the plugin it appears as follows :

![modal_lov_dialog3](https://user-images.githubusercontent.com/23289338/40816388-4ddbf32a-6555-11e8-8297-e6c959f1ccf5.png)

but after closing the dialog and re-open it the plugin appears as expected.

**Comment by mennooo** [comment]
Was caused by the fix for issue #2. The CSS file should no be **moved** from dialog page to top-level page, but **cloned**.
