### ISSUE TITLE
JS error raised when entering a non existing value in the search box

### ISSUE THREAD

**Issue by aymanwkh** [mennooo/orclapex-modal-lov#13]
when entering a value that does not match any of the existing data in the search box and press enter a JS error raised as follows :

TypeError: pValue is undefined[Learn More] modal-lov.js:683
	setValue modal-lov.js:683
	i http://localhost:8080/i/libraries/apex/minified/desktop_all.min.js:18:2613
	_returnSelectedRow modal-lov.js:578
	a.widget/</h[b]</< http://localhost:8080/i/libraries/apex/minified/desktop_all.min.js:29:6845
	_initKeyboardNavigation/< modal-lov.js:561
	dispatch http://localhost:8080/i/libraries/apex/minified/desktop_all.min.js:3:10263
	add/q.handle http://localhost:8080/i/libraries/apex/minified/desktop_all.min.js:3:8325

**Comment by mennooo** [comment]
This was caused by the fix for issue #9. Pressing enter will return the selected row, make an exception if no row is selected.
