### ISSUE TITLE
Navigation in IG

### ISSUE THREAD

**Issue by Ora-solution** [mennooo/orclapex-modal-lov#14]
Hi,

First of all, thank you so much for wonderful plugin and I would love to use this in my projects. But the issue I'm facing as per user perspective is that when using in IG the focus loses its position after selection value. Can you please suggest any workaround or fixed this issue.

Thanks.

**Comment by Ora-solution** [comment]
Thank you for your quick response. Yes exactly, but in my case just loosing the focus, so is there any event available which i can use to select cell again after selection.

Thanks.

**Comment by Ora-solution** [comment]
Thanks alot @mennooo for the new release, above issue has been resolved but i noticed that after getting focus back the cell was not in editable mode so i added below line in `_resetFocus` function and it's working perfect as per my requirement.

`this._grid.setEditMode(true)`

Thanks again.

**Comment by Ora-solution** [comment]
Another case of loosing focus was when we closed the dialog without selecting any value. I manage this by adding below row on modal close event.

`self._resetFocus()`

I hope you will consider these changes in a better way on upcoming release.

Thanks.

**Comment by mennooo** [comment]
This is fixed in V1.3.1
