### ISSUE TITLE
setting the read only property causes the plugin to not holding its value

### ISSUE THREAD

**Issue by aymanwkh** [mennooo/orclapex-modal-lov#15]
When setting the read only property for this plugin, the plugin can not hold the value that has been assigned to it programmaticaly (actually it displays the value but when saving the record the problem appears).

![modal1](https://user-images.githubusercontent.com/23289338/41030706-8edf86c6-6987-11e8-80c1-892b32e0b0f0.jpg)

**Comment by mennooo** [comment]
Hi, 

I'm changing the code to use the following:
https://docs.oracle.com/database/apex-5.1/AEAPI/PRINT_HIDDEN_IF_READONLY-Procedure.htm#AEAPI1365

Next version of the plug-in will be released soon.
