### ISSUE TITLE
Console error while clicking on column header in modal lov

### ISSUE THREAD

**Issue by santhoshkillari** [mennooo/orclapex-modal-lov#17]
Hi ,

First of all, i would like to say thank you for shared this amazing feature.

My question is, i am getting following errors while clicking on column headers, 
I think i missed out some thing to set/download. 

Please suggest me what are the files i need to import, if i missed to import extra files, 

![image](https://user-images.githubusercontent.com/34837897/41200654-902dfb24-6cc6-11e8-9e94-610c25d8d9b3.png)

![image](https://user-images.githubusercontent.com/34837897/41200880-5070817e-6cca-11e8-94c5-b3d042ba822f.png)

Please suggest me, How can we get rid of this ?

Thank you for your help.

**Comment by mennooo** [comment]
This will be fixed in V1.3
