### ISSUE TITLE
where do we put CSS & JavaScript on web server

### ISSUE THREAD

**Issue by sokosp** [mennooo/orclapex-modal-lov#19]
Dear Menoo, let me first thank you for your great work, 
i m trying to test it on my dev machine on a table that has a lot of postcodes.
in the readme you mention: 

"Additionally you can put the CSS & JavaScript on your web server and the PL/SQL code inside a package for better performance."

1.where would that be? in Tomcat or Apache that runs reverse proxy? 
Would we need then to edit the .SQL file to read from another location?
2. is there a guide/sample to add it in a package?

**Comment by mennooo** [comment]
Hi,

I'm not aware of a guide about how to move the code but I've found this blogpost.

https://blog.danielhochleitner.de/2018/02/11/oracle-apex-plugin-performance/

Typically you have a docroot specified in your webserver. This could be Tomcat or Apache, depending on your configuration. It containts the directory where all the static files of APEX are placed on installation or upgrade, starting with the #IMAGE_PREFIX# folder, usually `/i`. I like to have this structure:

APEX files
`<docroot>/i` 

Custom files
`<docroot>/custom`

Inside your custom folder you could add subfolders for the plug-in files.

`<docroot>/custom/plug-ins/modal-lov/js/`
`<docroot>/custom/plug-ins/modal-lov/css/`
