### ISSUE TITLE
multiple issues when calling from a dialog page

### ISSUE THREAD

**Issue by aymanwkh** [mennooo/orclapex-modal-lov#2]
I created a new application using Apex 18.1, when calling the plugin from a dialog page I notice these issues :
1. the search window stretches to the maximum width.
2. the first option disappears.
3. when mouse hovering the odd options disappear.

![modal_lov_dialog1](https://user-images.githubusercontent.com/23289338/40639297-f50f25ca-6318-11e8-8826-61a79d28c120.png)

![modal_lov_dialog2](https://user-images.githubusercontent.com/23289338/40639301-faffd25e-6318-11e8-9713-29725fe6fb71.png)

**Comment by mennooo** [comment]
Confirmed, if the top-level page does not have an instance of the plug-in, the CSS file is missing there. It should be dynamically inserted into that page.
