### ISSUE TITLE
Wrong number of columns selected in the LOV SQL query for CD_CENTRO_COSTO. See examples for valid statements.

### ISSUE THREAD

**Issue by Richard2605** [mennooo/orclapex-modal-lov#22]
![error](https://user-images.githubusercontent.com/8313677/42843144-35e6bfbe-89dd-11e8-94a5-5b3412e87eef.png)
Good afternoon I've been testing the plugin but it throws the following error when I implemented it in an interactive grid. This happens when I put an extra column in SQL query

**Comment by mennooo** [comment]
I've experienced the same issue and have a fix for it:  a metadata callback function should be specified in the plug-in attributes.
