### ISSUE TITLE
Iframe not supported :(

### ISSUE THREAD

**Issue by gecsafunk** [mennooo/orclapex-modal-lov#23]
First of all: big thanks for this Oracle Forms LOV like plugin!!
I would use it with Cordova library, so i would have to embed my apex page with the iframe tag, but in this case this plugin not working:

_Uncaught DOMException: Blocked a frame with origin "https://apex.oracle.com" from accessing a cross-origin frame.
    at a.(anonymous function).(anonymous function)._addCSSToTopLevel (https://apex.oracle.com/pls/apex/gecsafunk/r/13085/files/plugin/38286386934622231480/v342/modal-lov.js:1603:22)
    at a.(anonymous function).(anonymous function)._addCSSToTopLevel (https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js?v=18.1.0.00.45:29:6847)
    at a.(anonymous function).(anonymous function)._create (https://apex.oracle.com/pls/apex/gecsafunk/r/13085/files/plugin/38286386934622231480/v342/modal-lov.js:1208:12)
    at a.(anonymous function).(anonymous function)._create (https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js?v=18.1.0.00.45:29:6847)
    at a.(anonymous function).(anonymous function)._createWidget (https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js?v=18.1.0.00.45:29:8948)
    at new a.(anonymous function).(anonymous function) (https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js?v=18.1.0.00.45:29:6414)
    at HTMLInputElement.<anonymous> (https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js?v=18.1.0.00.45:29:8180)
    at Function.each (https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js?v=18.1.0.00.45:2:2815)
    at r.fn.init.each (https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js?v=18.1.0.00.45:2:1003)
    at r.fn.init.a.fn.(anonymous function) [as modalLov] (https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js?v=18.1.0.00.45:29:8090)
(anonymous) @ desktop_all.min.js?v=18.1.0.00.45:2
setTimeout (async)
r.readyException @ desktop_all.min.js?v=18.1.0.00.45:2
(anonymous) @ desktop_all.min.js?v=18.1.0.00.45:2
j @ desktop_all.min.js?v=18.1.0.00.45:2
k @ desktop_all.min.js?v=18.1.0.00.45:2
setTimeout (async)
(anonymous) @ desktop_all.min.js?v=18.1.0.00.45:2
i @ desktop_all.min.js?v=18.1.0.00.45:2
fireWith @ desktop_all.min.js?v=18.1.0.00.45:2
fire @ desktop_all.min.js?v=18.1.0.00.45:2
i @ desktop_all.min.js?v=18.1.0.00.45:2
fireWith @ desktop_all.min.js?v=18.1.0.00.45:2
k @ desktop_all.min.js?v=18.1.0.00.45:2
setTimeout (async)
(anonymous) @ desktop_all.min.js?v=18.1.0.00.45:2
i @ desktop_all.min.js?v=18.1.0.00.45:2
fireWith @ desktop_all.min.js?v=18.1.0.00.45:2
fire @ desktop_all.min.js?v=18.1.0.00.45:2
i @ desktop_all.min.js?v=18.1.0.00.45:2
fireWith @ desktop_all.min.js?v=18.1.0.00.45:2
ready @ desktop_all.min.js?v=18.1.0.00.45:2
R @ desktop_all.min.js?v=18.1.0.00.45:3_

If You want to try it:
https://www.w3schools.com/code/tryit.asp?filename=FTQ6WQ2EHM90

If You want to reproduce this problem, first time You have to set the "Embed in Frames" to "Allow" in the Shared components->Security->Browser security->Embed in Frames=Allow.

Thanks,
Geza Toth (SPS Media)

**Comment by mennooo** [comment]
Maybe I can add a check to see if the top level page is part of APEX and if not, try to recursively get parent page until the top level APEX page is found.

**Comment by gecsafunk** [comment]
Thanks for the suggestion, I hope that it will be the solution.

**Comment by mennooo** [comment]
Yes, should work with apex.util.getTopApex()

New version will be released soon.

**Comment by gecsafunk** [comment]
Thanks for your effort to support the iframe embedding! I tried the 1.2 and then the 1.3.1 versions..Unfortunately, it will not work iframe embedded, which would be very important for hybrid operation.
The parent calling page is an normal html (index.html), which would have to embed the apex page, like here (this apex example contains the latest version of the Modal LOV):
https://www.w3schools.com/code/tryit.asp?filename=FTQ6WQ2EHM90

Example:
<iframe src="https://apex.oracle.com/pls/apex/f?p=13085:1" height=500 width=500>
</iframe>

I got these error messages:

SecurityError: Permission denied to access property "document" on cross-origin object modal-lov.js:584

_initKeyboardNavigation
modal-lov.js:584
a.widget/</h[b]
https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js:29:6845
_onOpenDialog
modal-lov.js:130
a.widget/</h[b]
https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js:29:6845
open
modal-lov.js:179
_trigger
https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js:29:13155
open
https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js:34:2265
a.widget/</h[b]
https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js:29:6845
_init
https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js:34:533
a.widget/</h[b]
https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js:29:6845
_createWidget
https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js:29:9084
a.widget/a[i][b]
https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js:29:6409
a.widget.bridge/a.fn[b]/<
https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js:29:8180
each
https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js:2:2813
each
https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js:2:1001
a.widget.bridge/a.fn[b]
https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js:29:8085
_onLoad
modal-lov.js:166
a.widget/</h[b]
https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js:29:6845
success
modal-lov.js:386
l
https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js:15:6951
j/H.success
https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js:15:6299
i
https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js:2:27978
fireWith
https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js:2:28749
A
https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js:4:14201
send/c/<
https://apex.oracle.com/i/libraries/apex/minified/desktop_all.min.js:4:16491
