### ISSUE TITLE
Paste Not Recognized as Keystroke

### ISSUE THREAD

**Issue by MEYES3971** [mennooo/orclapex-modal-lov#26]
Hi Menno,

I have some users that like to paste (or use a scanner) to input text into one of your Modal LOV's that I am using in an APEX application. When pasting a copied value, it doesn't recognize the keystroke so it doesn't record that the field was changed and select the pasted value. Users are currently having to paste, enter a space, then back out the space for the LOV to recognize the pasted value. 

Any suggestions on how to handle this?

Shelly

**Comment by mennooo** [comment]
I will add an exception for the paste keystroke in the next release.
