### ISSUE TITLE
Font Awasome support

### ISSUE THREAD

**Issue by undvl** [mennooo/orclapex-modal-lov#30]
Hi, Menno.

Plugin has a broken markup with "Font Awasome" set for icons in theme properties.

![modal-lov__font-awasome-bug](https://user-images.githubusercontent.com/25033353/43884857-efe5f7b0-9bbf-11e8-8977-fcb39e461a5a.png)
![modal-lov__font-awasome-bug-2](https://user-images.githubusercontent.com/25033353/43884778-aced0c28-9bbf-11e8-87b8-a10b17cc2077.png)

With "Font APEX" all looks great.

**Comment by mennooo** [comment]
This will be fixed in V1.2, some HTML and CSS changed are needed.
