### ISSUE TITLE
Source Type Database Column case sensitive?

### ISSUE THREAD

**Issue by arintoul** [mennooo/orclapex-modal-lov#35]
Hi Menno, for a source Type of "Database Column" the "Database Column" value is case sensitive and will throw an error when processed (eg enter a lower case value). Is this case sensitivity intentional?

**Comment by mennooo** [comment]
Hi,

I hope I understand your use case correct. If not, please let me know. 

The source item is used as 'return value' for this plug-in. In most scenarios, this would be a number or varchar2 value. It seems correct to me that a value of 'KING' would identify another record than 'king'. These could be two rows in a table.

**Comment by arintoul** [comment]
Hi Menno,

I apologise for not including enough detail.

What I mean is the following;
PERSON_ID must be entered in upper case or it will fail when being processed by say an Automated Row Processing (DML) process. We're running APEX 5.1.3 although we're about to upgrade to 18.1
If PERSON_ID is entered in lower case as say person_id, the process will fail with an error to the effect that the column person_id is not found in the table, ie Column person_id not found in table PERSON.
It's as if it's looking for "person_id"
See image below for details...

I hope this helps.

Alan

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by arintoul** [comment]
Adding the image...

![image](https://user-images.githubusercontent.com/42745759/44730528-2b76ba00-aaaf-11e8-8112-48d9ba7ecdcc.png)

**Comment by mennooo** [comment]
I think this is standard APEX functionality. I didn't code anything to make this work. I could reproduce this error when using a regular text item. Indeed uppercase is required.
