### ISSUE TITLE
Javascript error loading css files

### ISSUE THREAD

**Issue by fabianurtlauf** [mennooo/orclapex-modal-lov#36]
Hi, 
I am trying to test the plug-in but i keep getting the following javascript error.

![image](https://user-images.githubusercontent.com/43388543/45712609-c3ba0900-bb5a-11e8-980c-c4361058d767.png)

I installed the plug-in following the readme instructions, is there any step i am missing or something i am doing wrong?.

Thanks you so much.

**Comment by mennooo** [comment]
Did you move the css and js files on your webserver? 
One thing I notice is that the rest of the files are the minified ones.
