### ISSUE TITLE
Not working on Oracle Apex  5.1.4.00.08 can you help me in it. it is showing the LOV but while clicking on LOV it is not opening any popup to select values. 

### ISSUE THREAD

**Issue by Sammeer-Ladckat** [mennooo/orclapex-modal-lov#43]
Not working on Oracle Apex  5.1.4.00.08 can you help me in it. it is showing the LOV but while clicking on LOV it is not opening any popup to select values.

**Comment by mennooo** [comment]
Do you see any errors in your browser? If so, but debug on to get a better understanding of the error and let me know.
