### ISSUE TITLE
ER : Next / Previous buttons 

### ISSUE THREAD

**Issue by APEXGru** [mennooo/orclapex-modal-lov#5]
How can we translate the Next / Previous buttons into (for instance) Vorige / Volgende ?

**Comment by mennooo** [comment]
The plug-in currently uses native text messages: 
* APEX.GV.NEXT_PAGE
* APEX.GV.PREV_PAGE

I checked and a better solution would be these messages:
* PAGINATION.NEXT
* PAGINATION.PREVIOUS

**Comment by mennooo** [comment]
Had to use the undocumented function `wwv_flow_lang.system_message` to get the value. Should be noted.

**Comment by rimblas** [comment]
Sounds familiar.
I ran into the exact same thing with the [JTLItem](https://github.com/rimblas/jtlitem) plugin.
I had to use
`wwv_flow_lang.system_message('APEX.PAGE_ITEM_IS_REQUIRED');`
