### ISSUE TITLE
Error loading modal-lov.js

### ISSUE THREAD

**Issue by eseisd** [mennooo/orclapex-modal-lov#51]
I'm very new to APEX.  Could you provide detailed instructions on how/where to move the JS and CSS files?

I imported the plugin .sql file and installed it.  I've added the Modal LOV to a page and configured it.  But when I run the app, the Modal LOV doesn't work.  Nothing happens when I click the search button and the CSS clearly hasn't been applied.

![modal-lov-error](https://user-images.githubusercontent.com/15090140/49450977-29a64c00-f7ac-11e8-8c9e-78e179c4dce2.JPG)

The web console reports the following errors:

Loading failed for the <script> with source “https://apexdev.rit.edu/ords/apex_ebs_extension/r/106/files/plugin/23158940847736069531/v460/modal-lov.js”. f:223:1
jQuery.Deferred exception: $(...).modalLov is not a function @https://apexdev.rit.edu/ords/f?p=106:1:13726830394923::::::235:32
@https://apexdev.rit.edu/ords/f?p=106:1:13726830394923::::::235:2
i@https://apexdev.rit.edu/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:2:27978
add@https://apexdev.rit.edu/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:2:28282
@https://apexdev.rit.edu/ords/f?p=106:1:13726830394923::::::231:67
a.init@https://apexdev.rit.edu/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:16:5303
@https://apexdev.rit.edu/ords/f?p=106:1:13726830394923::::::229:1
j@https://apexdev.rit.edu/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:2:29946
g/</k<@https://apexdev.rit.edu/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:2:30262
 undefined desktop_all.min.js:2:31515
TypeError: $(...).modalLov is not a function[Learn More] f:235:32
<anonymous>
https://apexdev.rit.edu/ords/f:235:32
<anonymous>
https://apexdev.rit.edu/ords/f:235:2
i
https://apexdev.rit.edu/i/libraries/apex/minified/desktop_all.min.js:2:27978
add
https://apexdev.rit.edu/i/libraries/apex/minified/desktop_all.min.js:2:28282
<anonymous>
https://apexdev.rit.edu/ords/f:231:67
a.init
https://apexdev.rit.edu/i/libraries/apex/minified/desktop_all.min.js:16:5303
<anonymous>
https://apexdev.rit.edu/ords/f:229:1
j
https://apexdev.rit.edu/i/libraries/apex/minified/desktop_all.min.js:2:29946
g/</k<
https://apexdev.rit.edu/i/libraries/apex/minified/desktop_all.min.js:2:30262

Thanks for your help.

**Comment by mennooo** [comment]
I think you need to configure RESTful services in APEX first.

https://docs.oracle.com/database/apex-18.2/HTMIG/configuring-Oracle-REST-data-services.htm#HTMIG29159

I checked your app, and other files like the app icon also couldn't be loaded.
Example: https://apexdev.rit.edu/ords/apex_ebs_extension/r/106/files/static/v4/app-icon.css
