### ISSUE TITLE
Problem with APEX_PLUGIN_UTIL.GET_DATA

### ISSUE THREAD

**Issue by Inolau** [mennooo/orclapex-modal-lov#61]
There seems to be an issue (in 18.2 anyway) with APEX_PLUGIN_UTIL.GET_DATA, called in procedure get_display_value: it adds a wildcard. Apex rewrites the query by adding a wildcard (see this debug info):

Rewrite SQL to: select a.* from (select "D", "R" from (<lov query>)
)a
where "R" like :p$_search_string||'%'

Since get_display_value returns the first row, you may and up with the wrong display value.

This is an example of the result:

<input type="text" id="P1_PLUGIN" name="P1_PLUGIN" class="apex-item-text modal-lov-item  " maxlength="" size="30" autocomplete="off" placeholder="" value="540" data-return-value="54">

As you can see: value="540", data-return-value="54"

**Comment by mennooo** [comment]
Fixed in V1.3.2
