### ISSUE TITLE
Cuts numbers short..

### ISSUE THREAD

**Issue by sokosp** [mennooo/orclapex-modal-lov#62]
e.g when we need to pull rowID 12345 from the DB, it will bring on the Apex page the ID 1234 (might skip numbers after first three-four digits)

e.g ID 12345 is AMSTERDAM and 1234 is LONDON in our DB.
When users enter AMSTERDAM (id 12345) on next page reload the MODAL-LOVE brings LONDON (id 1234)

**Comment by eseisd** [comment]
I think I'm experiencing the same issue.

**Comment by mennooo** [comment]
Fixed in V1.3.2

**Comment by sokosp** [comment]
Good work Mennoo, it created serious problems with data on Apex edit page.
Is it for 19.1 or 18.2 also? Thanks again for your kind contribution to Apex guys!

**Comment by mennooo** [comment]
In 1.3.3 it’s for all versions, not only 19.1. That was a mistake in 1.3.2.
