### ISSUE TITLE
BE CAREFUL - Wrong data!

### ISSUE THREAD

**Issue by dgielis** [mennooo/orclapex-modal-lov#63]
This is linked to issue #61 and #62 ; the result what is shown might be wrong.

The reason is that behind the scenes the plugin uses apex_plugin.get_data which does a search contains exact. But lets say your table contains:
60 Product 1
601 Product 2
603 Product 3

When you have a value of 60, the plugin will retrieve all those records. Depending the sort order you might get the wrong answer as it always takes the first entry.

**!!UNTIL THIS ISSUE IS FIXED, DON'T USE THIS PLUGIN, IT'S EXTREMELY DANGEROUS AS YOU POTENTIALLY SHOW THE WRONG DATA!!**

**Comment by mennooo** [comment]
Fixed in V1.3.2
