### ISSUE TITLE
Issue with Model lov in IG on Cascading LOV Parent Columns

### ISSUE THREAD

**Issue by arunasw** [mennooo/orclapex-modal-lov#68]
Hi ,
I am using Modal Lov in IG and recently after apex 19.1 upgrade it started to throw javascript error(red triangle appears  on top of developer tool) such as 
ERR-1002 Unable to find item ID for item "C009" in application "2600".
C009 is an existing column in IG and I am using in another column as a cascading lov parent column whose type is modal lov plugin .
There are such errors all over the page wherever I used Modal lov with cascading parent columns.
This issue is raised here also but no fix is given -
https://disqus.com/home/discussion/menn-ooo/plug_in_modal_lov/
Please Help.
--Thanks

**Comment by mennooo** [comment]
Hi,

I'm afraid the APEX code has changed in 19.1 regarding AJAX callbacks for Interactive Grids.
The best thing to do is wait for APEX 19.2, which will include a new Popup LOV item type which is the way forward and supported by the APEX team.

**Comment by arunasw** [comment]
Thanks for quick reply
